Add workaround for a rustc bug (rust/43081)
This works around a compiler bug which can sometimes cause E0425 when
the `#[methods]` macro is used. The error, when triggered, would show up as
`error[E0425]: cannot find value `builder` in this scope` without any
span information.